spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        druid:
            first:
                url: jdbc:mysql://192.168.38.23:3306/tz?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
                username: root
                password: Orhon_zhtz
            second:
                url: jdbc:mysql://192.168.38.23:3306/tz?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
                username: root
                password: Orhon_zhtz
            initial-size: 10
            max-active: 100
            min-idle: 10
            max-wait: 60000
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            validation-query: SELECT 1 FROM DUAL
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            stat-view-servlet:
                enabled: true
                url-pattern: /druid/*
                #login-username: admin
                #login-password: admin
            filter:
                stat:
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: true
                wall:
                    config:
                        multi-statement-allow: true
                        
reply:
  hour: 7500000   #1000*60*60*2
  
upload:
  filepath: /orhon/upload/
