spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.3.100:3306/ole_test?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false 
    username: root
    password: Aoxiang@927
    initialSize: 5
    minIdle: 5
    maxActive: 200
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    servlet:
      load-on-startup: 1
  redis:
    host: localhost
    port: 6379
  jpa:
    show-sql: true
  activiti:
    asyncExecutorActivate: false
    asyncExecutorEnabled : false

mybatis:
  type-aliases-package: com.orhonit.ole.sys.model
  mapper-locations: classpath*:/mybatis-mappers/*
files:
  path: ${file-path:D:/ole-upload/person}
  versionPath: ${file-path:/appVerson}
  bannerPath: ${file-path:D:/ole-upload/appBanner}
  punishBill: ${file-path:D:/ole-upload/punishBill}
logging:
  config: classpath:logback-spring.xml
log:
  level:
    root: info
    my: debug
  file: /home/enforce/ole-enforce.log
  maxsize: 30MB
token:
  expire:
    seconds: 86400
server:
  port: 8081
  context-path: /enforce
  
docTemplate:
  convertTag: ole
  notConvert:
    tagNames: partyInfo,caseInfo,flowComment,checkUser,potence
    
flowModule:
  ip: 127.0.0.1
  port: 8080
  modulePath: /flow
  api:
    - path: /getUserTask
      method: get
      desc: 获取当前登录人代办任务
    - path: /createTask
      method: post
      desc: 创建流程
upload:
  winPath: D:\\ole-upload\\
  otherPath: /var/ole/ole-upload/
  winCaseCatalogPath: D:\\ole-upload\\case-catalog\\
  otherCaseCatalogPath: /var/ole/ole-upload/case-catalog/
  winTemp: D:\\ole-upload\\temp\\
  otherTemp: /var/ole/ole-upload/temp/
  serverUrl: http://111.235.156.244:8085/
spring.mvc.view.prefix: /WEB-INF/jsp/
spring.mvc.view.suffix: .jsp

# ip鉴权
share:
  urls:
    - url: 192.168.0.106
      desc: 本地测试地址
    - url: 1.2.3.4
      desc: 城管局