spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.100.82.50:3306/ole?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false 
    username: ole
    password: ole_2018
mybatis:
  type-aliases-package: com.orhonit.ole.sys.model
  mapper-locations: classpath*:/mybatis-mappers/*
files:
  path: ${file-path:E:/ole-upload/person}
logging:
  level:
    root: info
    com.zw: debug