spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.3.99:3306/ole?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: OrhonGoolDB@7893
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    servlet:
      load-on-startup: 1
  redis:
    host: 192.168.3.99
    port: 6379
  jpa:
    show-sql: true
  activiti:
    asyncExecutorActivate: false
    asyncExecutorEnabled : false

mybatis:
  type-aliases-package: com.orhonit.ole.sys.model
  mapper-locations: classpath*:/mybatis-mappers/*
files:
  path: ${file-path:/orhon/ole/ole-upload/person}
  versionPath: ${file-path:/orhon/ole/ole-upload/appVerson}
  bannerPath: ${file-path:/orhon/ole/ole-upload/appBanner}
logging:
  config: classpath:logback-spring.xml
log:
  level:
    root: info
    my: debug
  file: /orhon/ole/log/tts/ole-tts.log
  maxsize: 30MB
token:
  expire:
    seconds: 86400
server:
  port: 8083
  context-path: /tts
  
docTemplate:
  convertTag: ole
  notConvert:
    tagNames: partyInfo,caseInfo,flowComment,checkUser

upload:
  winPath: E:\\ole-upload\\
  otherPath: /orhon/ole/ole-upload/
  winCaseCatalogPath: E:\\ole-upload\\case-catalog\\
  otherCaseCatalogPath: /orhon/ole/ole-upload/case-catalog/
  winTemp: E:\\ole-upload\\temp\\
  otherTemp: /orhon/ole/ole-upload/temp/
# serverUrl: http://47.100.82.50/
  serverUrl: http://111.235.156.244:80/

