spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.3.100:3306/ole_test?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false 
    username: root
    password: Aoxiang@927
    initialSize: 5
    minIdle: 5
    maxActive: 100
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    servlet:
      load-on-startup: 1
  redis:
    host: 192.168.3.99
    port: 6379
mybatis:
  type-aliases-package: com.orhonit.ole.sys.model
  mapper-locations: classpath*:/mybatis-mappers/*
files:
  path: ${file-path:/orhon/ole/ole-upload/person}
  versionPath: ${file-path:/orhon/ole/ole-upload/appVerson}
  bannerPath: ${file-path:/orhon/ole/ole-upload/appBanner}
logging:
  config: classpath:logback-spring.xml
log:
  level:
    root: info
    my: debug
  file: /orhon/ole/log/auth/ole-auth.log
  maxsize: 30MB
token:
  expire:
    seconds: 86400
server:
  port: 8088
  context-path: /auth
ole:
  sso:
    enforce: http://111.235.156.244:8083/enforce/sso/login
    base: http://111.235.156.244:8084/base/sso/login
    report: http://111.235.156.244:8084/report/sso/login
    ps: http://111.235.156.244:8084/ps/#page=subSystem
    pa: http://111.235.156.244:8084/pa/sso/login
    auth: http://111.235.156.244:8084/auth
    tts: http://111.235.156.244:8084/tts/sso/login
    tokenExpire: 600
upload:
  serverUrl: http://111.235.156.244:8085/